### ISSUE TITLE
Feature Request: add dataview tasks method compatibility

### ISSUE THREAD

**Issue by Jack-Chronicle** [therden/packrat#11]
The plugin only checks for the emoji (u+1F501) which isn't used when Tasks is set to the dataview method, and can be easily changed by adding [repeat:: to the trigger check, would be awesome if this got added officially instead of needing to be done manually
And hopefully the plugin isn't 100% dead

**Comment by therden** [comment]
A belated Thank You, @Jack-Chronicle, for your suggestion.

The _Packrat_ plug-in was developed before the [Tasks](https://github.com/obsidian-tasks-group/obsidian-tasks) plugin acquired support for the [Dataview](https://github.com/blacksmithgu/obsidian-dataview) plugin's syntax.

I hope next month (January 2024) to be able to allocate some time to perform some long-postponed maintenance on _Packrat_.  

I hope and expect that your suggestion will be relatively easy for me to implement -- and, if so, I will gladly do so.

**Comment by therden** [comment]
@Jack-Chronicle:  **Packrat** release 1.1.1, published today, implements your suggestion to match **Tasks**' support for **Dataview**-style inline fields.

Thank you again.
