### ISSUE TITLE
Build instructions?

### ISSUE THREAD

**Issue by tommoyer** [therden/packrat#13]
Are there build instructions that can be shared for getting this to build?

**Comment by therden** [comment]
Hello @tommoyer.  

Please see the README.md page for the Github-hosted repo for the [Obsidian sample plugin](https://github.com/obsidianmd/obsidian-sample-plugin) (from which, I believe, all Obsidian plugins are derived.)

In particular, the "How to Use" section may be of interest.

**Comment by therden** [comment]
Hello again @tommoyer.

I realized today that a file necessary to successfully run the `npm run dev` command -- esbuild.config.mjs -- was missing from the **Packrat** plugin's repo on Github.  I've now added it.

I apologize for the inconvenience.
