### ISSUE TITLE
If archive file already exists I get an error saying it does.

### ISSUE THREAD

**Issue by DudeThatsErin** [therden/packrat#15]
Can this not append or prepend or whatever to an existing file?

It doesn't seem to be working on my iPhone. I plan to test tomorrow on my computer.

**Comment by therden** [comment]
Yes, Packrat will append completed recurring tasks that contain the string to trigger the Archive action to an existing file.

How did things worked on your computer (as opposed to your iPhone)?

**Comment by therden** [comment]
Closing issue for now; willing to re-open if @DudeThatsErin (or anyone else) can identify the conditions necessary to reproduce it.
