### ISSUE TITLE
Add command to process completed recurring tasks from the entire vault

### ISSUE THREAD

**Issue by therden** [therden/packrat#2]
@kmaustral wrote:

"The problem is that I have recurring tasks spread over the vault. There is usually one recurring task for each project that schedules time to spend on it.  I have around 30 projects. It would be easier if there was a command to delete all past tasks across the vault."

_Originally posted in https://github.com/therden/packrat/issues/1#issuecomment-1136962129_

**Comment by therden** [comment]
Hello @kmaustral.

If my current, renewed efforts to get equivalent real-time processing of completed items added to **Tasks** itself are unsuccessful, then I intend to add a second **Packrat** command for "whole vault" scanning that will rely on a note Property (formerly YAML front-matter key:value) to identify each note on which **Packrat** should operate.

For now, however, I am Closing this issue.

**Comment by kmaustral** [comment]
Thanks and good luck.
