### ISSUE TITLE
Specify alternative archive file

### ISSUE THREAD

**Issue by therden** [therden/packrat#8]
_Originally posted by @Azurewren in https://github.com/therden/packrat/discussions/5#discussioncomment-3021724_

I was looking for a way to have multiple archive files. Perhaps there could be a way to define what archive file to place a task in, otherwise use the default archive file defined in the settings?

**Comment by therden** [comment]
Hello @azurewren.

I don't know whether I'll be _capable_ of implementing this idea, but I'm willing to consider it.  

Please say more about how you envision using it.  At what level would you want to be able to specify the archive file to which completed tasks with the appropriate trigger should be moved?

- for all notes within a particular directory of your vault?
- for all tasks within an particular note?
- for all tasks listed beneath a particular header?
- on a task-by-task basis?

**Comment by Azurewren** [comment]
At minimum there should be a default file, (like it is currently) where archived files can be placed. That shouldn't change.

Possible methods of implementation could be approached a variety of ways. You could define an archive file...

- per folder. Maybe use a prefix/postfix (defined in the setting) connected with the folder name, or just an static archive file name per folder. Perhaps Folder Notes could aid in this by defining the archive file in the frontmatter of a folder note. This I think is a stretch though.

- per file. The archive file name could be defined in the file frontmatter, or use a prefix/postfix (defined in the setting) connected with the filename (eg: tasks in 'gaming.md' when archived could be sent to 'gaming_archive.md'). 

- per task. eg: maybe define the archive file between the %%'s (%%done_log [[task archive]]%%

- per tag. Is it possible to connect tasks and tags and have them sent to specific archive files.. It would have to be defined in the settings I think..

**Comment by therden** [comment]
Hello @Azurewren.

With apologies for the overlong "radio silence":  if my current efforts to add real-time **Packrat**-like functionality to **Tasks** itself are unsuccessful, I will try to add _note file-specific_ support to **Packrat**, using a Property (formerly YAML front matter) to set the archive file location and name to log completed tasks.

For now, however, I am Closing this issue.
