### ISSUE TITLE
can't get to work at all

### ISSUE THREAD

**Issue by pcause** [therden/packrat#9]
in last few builds (inders and released) can't seem to get this to work at all.  I have a Note that has all my recurring tasks.  I can see the checked/competed task.  include %%done_del%%  in the task and when i run, no change at all to the note

**Comment by Azurewren** [comment]
I am encountering the same issue.

**Comment by therden** [comment]
Hello @pcause and @Azurewren -- I apologize for the delay in my reply.  

I haven't updated Packrat's code for a couple of months, but I _have_ updated Obsidian and Tasks to their current versions (**0.15.9** and **1.11.1**, respectively) and the plugin still works for me.

If you'll provide a sample of one or more instances of completed, recurring Tasks that include Packrat triggers which the plugin isn't acting upon as expected, I'd be willing to try to figure out why.

Or, if you'd prefer, you could copy the example checklist from [the repo's README.md file](https://github.com/therden/packrat#im-not-sure-i-follow-how-this-is-supposed-to-work-can-you-give-an-example) into a temporary note in your vault, run the **"Packrat: Process completed recurring Tasks within the active note"** command on it, and (after comparing to the expected result shown in the README) let me know the result.

**Comment by therden** [comment]
Glad to hear it!  I'll close this issue now.
